apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dotnet
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-dotnet
  template:
    metadata:
      labels:
        app: test-dotnet
    spec:
      containers:
        - name: test-dotnet
          image: localhost:5000/test-dotnet:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8010
          env:
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=test-dotnet,service.namespace=TestApps"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://collector-collector.opentelemetry-operator-system.svc.cluster.local:4317"
            - name: OTEL_TRACES_SAMPLER
              value: "parentbased_always_on"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
---
apiVersion: v1
kind: Service
metadata:
  name: test-dotnet
  namespace: default
spec:
  selector:
    app: test-dotnet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8010
      nodePort: 30010
  type: NodePort
